### ISSUE TITLE
Privacy Policy copy

### ISSUE THREAD

**Issue by rosejbon** [neontribe/ca-hospice-hope#12]
## Description

We need to have a privacy policy on the site to describe how we are using cookies and what will happen with people data.

Here is a link to the privacy policy: https://docs.google.com/document/d/1HxiUJC9yihbY1DpUaBs3wVord6F2SjEYnzusys68Alw/edit?usp=sharing

## Plan

- [ ] Add copy to privacy policy page from Google Doc

## Acceptance Criteria

- [x] It is understood how we use peoples data and where it is stored
- [ ] Copy matched Google Docs

**Comment by j-gynn** [comment]
@roseb04 On the Contemplating Action website there's a company info list on the Privacy Policy page - as there is no equivalent in the Privacy Policy provided, are the clients likely to need/want this?

**Comment by j-gynn** [comment]
@roseb04 I have a question about the Hospice Hope Privacy Policy

> Improve improving our ability to serve you relevant content via cookies

This... doesn't make sense, I'd appreciate some input here.

**Comment by j-gynn** [comment]
RE: Making the Privacy content tags more generic:

>Such as I understand it, the best way to genericise the tags in the Privacy page would be to define them loosely following the pattern of the page (in this case "Privacy") followed directly by either:
>
>Title - just for the title of the page in this instance
>ContentTitle (or ContentT) - for headings for paragraphs
>Paragraph (or Para or P) - for paragraphs
>
>followed by a number when required?
>
>Potentially this could be overly generic. Feedback?

**Comment by rosejbon** [comment]
> @roseb04 I have a question about the Hospice Hope Privacy Policy
> 
> > Improve improving our ability to serve you relevant content via cookies
> 
> This... doesn't make sense, I'd appreciate some input here.

We probably could reword that. Basically it is saying we are using Google Analytic cookies to improve the content of the website

**Comment by rosejbon** [comment]
> @roseb04 On the Contemplating Action website there's a company info list on the Privacy Policy page - as there is no equivalent in the Privacy Policy provided, are the clients likely to need/want this?

I'm not too worried about this for the Hospice Hope site as the Privacy Policy is their own and they haven't put that info in.

**Comment by katjam** [comment]
@RabidGamer I think you can do this one now the Keys have been updated in the core.

**Comment by katjam** [comment]
Mostly done with: https://github.com/neontribe/ca-hospice-hope/pull/25

Will add final 2 sections after refactor of rendering template for Privacy page

**Comment by Hoolean** [comment]
Seems to be as friendly and understandable as a Privacy Policy can be :)

I have a few highly pedantic issues, though I'm doubtful they're enough to fail any of the Acceptance Criteria:
* Most double spaces in the original copy were spotted but two double spaces have crept into the site
![image](https://user-images.githubusercontent.com/2150762/63429412-d9424d80-c411-11e9-9c06-60a8d45d3f82.png)
![image](https://user-images.githubusercontent.com/2150762/63429592-62f21b00-c412-11e9-96c2-b7b8c800a613.png)
* The policy refers to a placeholder site - this is probably intentional but I thought it best to document it somewhere
![image](https://user-images.githubusercontent.com/2150762/63429736-c67c4880-c412-11e9-8ef2-33674de9c86a.png)
* `administrator@hospicehope.org.uk` is linked inline when referred to in the copy document but not on the site
* Minor typo
![image](https://user-images.githubusercontent.com/2150762/63429688-a51b5c80-c412-11e9-8420-ec75288d322d.png)
* I found the mention of a paid annual subscription here a little confusing
![image](https://user-images.githubusercontent.com/2150762/63429856-2377fe80-c413-11e9-8a81-2945f10f947e.png)
